name: 'Continuous Delivery'

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx==0.23.0 anyio==3.6.0
        pip install -r requirements-test.txt
        
    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make
        
    - name: Build Docker image
      run: |
        docker build -t latam-challenge-api:${{ github.sha }} .
        docker build -t latam-challenge-api:latest .
        
    - name: Test Docker image
      run: |
        docker run -d -p 8080:8080 --name test-api latam-challenge-api:latest
        sleep 30
        curl -f http://localhost:8080/health || exit 1
        docker stop test-api
        
    - name: Deployment successful
      run: |
        echo "✅ Docker image built successfully"
        echo "✅ Health check passed"  
        echo "🚀 Ready for production deployment"